### ISSUE TITLE
Remove `build/` folder

### ISSUE THREAD

**Issue by deadcoder0904** [colehollant/mq-viewer#1]
It makes cloning really big. Need to download all 3 Electron versions for different OSes.

You can either add them to the `Releases` tab & add `build/` folder to `.gitignore`. Makes cloning easy :)

**Comment by colehollant** [comment]
Ah, yup, meant to toss it up in the ol' bucket, but I forgot. Thank you!

**Comment by deadcoder0904** [comment]
Cool, just a nitpick, u can also add `.DS_Store` to `.gitignore` if u want.

Bdw I just tried MQ-Viewer, it’s works nicely. The `.dmg` didn’t work but I cloned the repo & then started it & it worked.

Are you planning to maintain this thing with new features or just going to complete the todos mentioned in the repo?

I also read the code which is damn short ~1000 LOCs. How long did it take u to make this?

Sorry for all the questions, just curious :)

**Comment by nicolehollant** [comment]
Fair enough, I'll toss it in the ignore. The .dmg probably shouldn't work
since I've yet to actually pay for my Apple Developer account, I will one
day...

I'll keep up with it a bit. I probably won't be super active with it
throughout the rest of the semester, but I'll work on it here and there. It
was just a weekend project cause I figured I could get it to a reasonable
state pretty quickly. It's nothing too complicated, more or less just
webviews and dealing with appdata—themes are also a lot easier if you steal
colors from apple haha.

**Comment by deadcoder0904** [comment]
I don’t think you actually need Apple Developer account for the `.dmg` to work.

The Developer Account is needed to show no warnings like `“Are u sure you want to open it? It’s damaged. Downloaded from the internet. Yada yada…”`.

Right now, it doesn’t open even directly.

And thanks for all the answers. Good luck with your semester 👍
